### ISSUE TITLE
decompiler at sf.net is now found at uxmal/reko on GitHub

### ISSUE THREAD

**Issue by uxmal** [rfalke/decompiler-subjects#1]
Just letting you know in case you weren't aware.

**Comment by rfalke** [comment]
Thank you. I was indeed no aware of it. I like the name and plan to update the files for reko.

Currently https://github.com/uxmal/reko/issues/466 prevents an update of the files.

**Comment by rfalke** [comment]
I used linux with mono and ulimit. The result of running reko 0.7.0 is https://github.com/rfalke/decompiler-subjects/commit/230ec96795d37b81fd1a4244822698c59efa642a
